### ISSUE TITLE
Input class should only be applied to html input tag

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#133]
In some places in the app, such as the immunization page, the input class is being applied to a parent level div which is creating a double border around the input. It's not needed here, as the native html `input` tag takes care of what's needed on the specific element.

<img width="1405" alt="Screen Shot 2019-04-01 at 2 09 18 PM" src="https://user-images.githubusercontent.com/20425828/55371225-4af51b80-54b2-11e9-9318-4cae76fc3cf2.png">

**Comment by bryan-gilbert** [comment]
In my next commit the look of the date pickers will change and I think will address the issue you saw.  Yet, the commit will not change the code as shown in the screenshot because that code is coming from the 3rd party date picker component.  In other words, the 3rd party component is applying the 'input' class to the wrapper div.  But I don't think that will be a problem with the other changes I've made to our code. See _form.scss (in my next commit)
