### ISSUE TITLE
Do not allow the same assignment external ID to be used more than once

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#219]
Re: May 29th meeting with Dave, Clint, Amanda and Bryan

**Comment by bryan-gilbert** [comment]
Assignments have a fields called "externalId" which is used to link the assignment with the LMS (Moodle, etc).  The user of the LMS needs to know that when they use an externalId they will get a specific assignment in the EdEHR.  Yet, at the moment, it is possible to create two or more assignments with the same externalId.  
Make the externalId unique for any given tool consumer.  So that when a user edits or creates a new assignment, in the EdEHR, they can't accidentally create a duplicate.

The API must ensure that externalId's are unique within a tool consumer's data space.
The editing dialogs must (at least) warn and (ideally) prevent users from attempting to create a duplicate.
