### ISSUE TITLE
Duplicate seed data

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#321]
## User story
As a seed creator user,
I want to be able to be able to duplicate a seed
So that I don't have to start from scratch when creating new seeds

## Description
Duplicate seed functionality.

## Expected behaviour/Acceptance criteria
- Button to duplicate is in edit, delete view block of buttons.
- Button label is `duplicate`
- Name of the duplicated seed is `COPY OF [copied seed name]`
- User has option of duplicated associated documents or leaving them out.
- A new folder for associated documents is created with each new seed.

**Comment by mandily-p** [comment]
Related to #326 - Incremental seeding / laddered cases

**Comment by bryan-gilbert** [comment]
Update acceptance criteria:  We do not need the last two tasks because we do not, yet, have per seed data files.  Remove the following until we have per seed documents.

- User has option of duplicated associated documents or leaving them out.
- A new folder for associated documents is created with each new seed.
