### ISSUE TITLE
"Send evaluation to student" button does not appear in dashboard

### ISSUE THREAD

**Issue by mandily-p** [BCcampus/edehr#364]
## Steps to reproduce
1. Login as a student and submit an assignment
2. Login as an instructor and leave evaluation notes on that assignment and save.
3. View the dashboard and notice only 2 buttons appear instead of 3 - "Send back for edits" and "Evaluate student work".

## Solution
The instructor should be able to see all three buttons appear after they have left evaluation notes: "Send evaluation to student"(primary button style), "Send back for edits"(secondary button style) and "Evaluate student work"(secondary button style)

**Comment by bryan-gilbert** [comment]
To be clear step 2 is 
- log on as instructor
- evaluate the work in the ehr AND add an evaluation note AND save
because then, for me on the BCC server when I return to the dashboard all three buttons appear. The send eval to student is only visible once there is some evaluation notes.  We could change this and make if always visible yet that would let instructors send no notes.

**Comment by mandily-p** [comment]
Bryan was unable to reproduce. Investigate what sequence creates this problem.

**Comment by mandily-p** [comment]
I can no longer reproduce either. closing the ticket.
